<?php
$file = 'resources/views/pdfbuilder/pdf.blade.php';
$content = file_get_contents($file);

// 1. Remove the global logo injection I added earlier
$globalLogoPattern = '/<\?php if \(\!empty\(\$_customLogoBase64ForPages\)\): \?>\s*<div style="position:fixed; bottom:55px; right:40px; z-index:999;">\s*<img src="<\?= \$_customLogoBase64ForPages \?>" style="max-width:120px; max-height:65px; object-fit:contain; background:#fff; border-radius:4px; padding:3px;">\s*<\/div>\s*<\?php endif; \?>/s';
$content = preg_replace($globalLogoPattern, '', $content);

// 2. Inject the logo into the Generated by footers
$logoHtml = "\n                    <?php if (!empty(\$_customLogoBase64ForPages)): ?>\n                    <div style=\"position:absolute; bottom:45px; right:30px; z-index:999;\">\n                        <img src=\"<?= \$_customLogoBase64ForPages ?>\" style=\"max-width:120px; max-height:65px; object-fit:contain; background:#fff; border-radius:4px; padding:3px;\">\n                    </div>\n                    <?php endif; ?>";

// There are two types of Generated by
// Generated by <?= esc($globalCompanyName) ? >
// Generated by <?= esc($companyName) ? >

$content = preg_replace('/(Generated by <\?= esc\(\$globalCompanyName\) \?>)/', '$1' . $logoHtml, $content);
$content = preg_replace('/(Generated by <\?= esc\(\$companyName\) \?>)/', '$1' . $logoHtml, $content);

file_put_contents($file, $content);
echo "Fixed logo injection.\n";
