<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {
            font-family: 'Montserrat', 'Helvetica', 'Arial', sans-serif;
            color: #333;
            margin: 0;
            padding: 0;
        }
        .page {
            position: relative;
            min-height: 100vh;
            padding: 40px;
            font-family: 'Montserrat', sans-serif;
        }
        .header-title {
            color: #000; /* Matching the screenshot's dark gold */
            font-size: 22px;
            font-weight: bold;
            text-transform: uppercase;
            padding-bottom: 10px;
            margin-bottom: 30px;
        }
        .description {
            font-size: 14.5px;
            line-height: 1.5;
            color: #333;
        }
    </style>
</head>
<body>
    <div class="page">
        @php
            $logoBase64 = null;
            $companySettings = \App\Models\Setting::pluck('value', 'key')->toArray();
            if (!empty($companySettings['company_logo_path'])) {
                $diskPath = storage_path('app/public/' . $companySettings['company_logo_path']);
                if (file_exists($diskPath)) {
                    $logoBase64 = 'data:image/' . pathinfo($diskPath, PATHINFO_EXTENSION) . ';base64,' . base64_encode(file_get_contents($diskPath));
                }
            }
            if (!$logoBase64) {
                $userLogo = $estimate->user->company_logo ?? null;
                if ($userLogo) {
                    $legacyPath = public_path('assets/img/profile/' . $userLogo);
                    if (file_exists($legacyPath)) {
                        $logoBase64 = 'data:image/' . pathinfo($legacyPath, PATHINFO_EXTENSION) . ';base64,' . base64_encode(file_get_contents($legacyPath));
                    }
                }
            }
        @endphp
    <!-- Header -->
    <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom: 30px;">
        <tr>
            <td width="50%" align="left" valign="top">
                <div style="font-size: 18px; color: #333; font-family: 'Montserrat', sans-serif;">
                    {{ (float)($estimate->quantity ?? 0) }}kW Ongrid {{ $estimate->type ?? 'Proposal' }}
                </div>
            </td>
            <td width="50%" align="right" valign="top">
                @if($logoBase64)
                    <img src="{{ $logoBase64 }}" alt="Company Logo" style="max-width: 160px; max-height: 55px; height: auto; object-fit: contain;">
                @endif
            </td>
        </tr>
    </table>
    
    <div class="header-title">SOLAR PV MODULE</div>
    <div class="description">
        Technical specifications and their description for the grid system Solar Photovoltaic Plant are given in the following sections.
    </div>

    <div style="position: absolute; bottom: 10px; left: 0; right: 0;">
        <table width="100%" cellpadding="0" cellspacing="0" style="background: #fff; color: #4b9349; height: 40px; border-top: 1px solid #4b9349;">
            <tr>
                <td width="33.33%" style="padding:10px; font-family: 'Montserrat', sans-serif;">
                    {{ (float)($estimate->quantity ?? 0) }}kW Ongrid {{ strtolower($estimate->doc_type ?? '') === 'invoice' ? 'Invoice' : 'Proposal' }}
                </td>
                <td width="33.33%" align="center" style="padding:10px; font-family: 'Montserrat', sans-serif;">
                    PAGE {{ $pageNumber ?? '' }}
                </td>
                <td width="33.33%" align="right" style="padding:10px; font-family: 'Montserrat', sans-serif; white-space:nowrap;">
                    Generated by {{ $companyName ?? 'MBT Solar' }}
                </td>
            </tr>
        </table>
    </div>
    </div>
</body>
</html>
