<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { box-sizing: border-box; }
        @page { margin: 0; }
        body {
            font-family: 'Montserrat', 'Helvetica', 'Arial', sans-serif;
            color: #333;
            margin: 0;
            padding: 0;
        }
        .page {
            position: relative;
            min-height: 100vh;
            padding: 40px;
            font-family: 'Montserrat', sans-serif;
        }
        .header-title {
            color: #000;
            font-size: 22px;
            font-weight: bold;
            text-transform: uppercase;
            padding-bottom: 10px;
            margin-bottom: 20px;
        }
        .description {
            font-size: 14.5px;
            line-height: 1.5;
            color: #333;
            margin-bottom: 20px;
        }
        .img-container {
            text-align: center;
        }
        .img-container img {
            width: 100%;
            height: auto;
            max-height: 800px;
            object-fit: contain;
        }
        .prop-footer {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            padding: 15px 56px;
            background-color: #ffffff;
            border-top: 1px solid #4CAF50;
            font-size: 11px;
            color: #4CAF50;
        }
    </style>
</head>
<body>
    <div class="page">
        <!-- Header -->
        <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom: 30px;">
            <tr>
                <td width="100%" align="left" valign="top">
                    <div style="font-size: 18px; color: #333; font-family: 'Montserrat', sans-serif;">
                        {{ (float)($estimate->quantity ?? 0) }}kW Ongrid {{ $estimate->type ?? 'Proposal' }}
                    </div>
                </td>
            </tr>
        </table>
        
        <div class="header-title">SOLAR PV MODULE</div>
    <div class="description">
        Technical specifications and their description for the grid system Solar Photovoltaic Plant are given in the following sections.
    </div>
    
    <div class="img-container">
        @php
            $normalizedPath = '';
            if (!empty($imagePath)) {
                if (function_exists('normalize_pdf_image')) {
                    $normalizedPath = normalize_pdf_image($imagePath);
                } else {
                    $diskPath = storage_path('app/public/' . $imagePath);
                    if (file_exists($diskPath)) {
                        $normalizedPath = 'data:image/' . pathinfo($diskPath, PATHINFO_EXTENSION) . ';base64,' . base64_encode(file_get_contents($diskPath));
                    }
                }
            }
        @endphp
        @if($normalizedPath)
            <img src="{{ $normalizedPath }}" alt="Datasheet">
        @endif
    </div>

    <div style="position: absolute; bottom: 10px; left: 0; right: 0;">
        <table width="100%" cellpadding="0" cellspacing="0" style="background: #fff; color: #4b9349; height: 40px; border-top: 1px solid #4b9349;">
            <tr>
                <td width="33.33%" style="padding:10px; font-family: 'Montserrat', sans-serif;">
                    {{ (float)($estimate->quantity ?? 0) }}kW Ongrid {{ strtolower($estimate->doc_type ?? '') === 'invoice' ? 'Invoice' : 'Proposal' }}
                </td>
                <td width="33.33%" align="center" style="padding:10px; font-family: 'Montserrat', sans-serif;">
                    PAGE {{ $pageNumber ?? '' }}
                </td>
                <td width="33.33%" align="right" style="padding:10px; font-family: 'Montserrat', sans-serif; white-space:nowrap;">
                    Generated by {{ $companyName ?? 'MBT Solar' }}
                </td>
            </tr>
        </table>
    </div>
    </div>
</body>
</html>
